### ISSUE TITLE
Question: Recieving Messages on All Channels

### ISSUE THREAD

**Issue by Hockeyfan360** [nerd/Discord4J#15]
Basically the title.

I got a nice little bot running well, but I want to make the bot able to receive messages from all users on all channels. Is this possible? I have tried contacting others in the discord chat, but no one seems to be replying. I am utilizing the MessageReceiveEvent, should I be using a different one?

**Comment by austinv11** [comment]
You should be getting it as it works for me. You should make sure the bot is invited to all the channels you want it to get messages from.

**Comment by Hockeyfan360** [comment]
@austinv11 I feel like an idiot :P Thanks!
