### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by austinv11** [nerd/Discord4J#18]
For awhile now the only commits from you have been to merge my pull requests and you disappeared from the #java_discord4j server. So I am wondering, do you plan on developing for this still?

**Comment by nerd** [comment]
short answer: yes
long answer: yes it's dead

**Comment by austinv11** [comment]
I would like to maintain a fork of this project. Is it possible to add a notice to your README to lead to my maintained fork here https://github.com/austinv11/Discord4J?
