### ISSUE TITLE
Maven repo?

### ISSUE THREAD

**Issue by Sponges** [nerd/Discord4J#2]
Is there a maven repository for this?

**Comment by nerd** [comment]
Not currently. If you could provide me with some resources on this matter, I'd be happy to set it up.

**Comment by SpongyBacon** [comment]
Maybe once I get a new dedi. However, this might be of interest?
http://kwebble.com/blog/2014/02/19/use-github-to-host-your-own-maven-repo

**Comment by austinv11** [comment]
You might want to consider [Bintray](https://bintray.com/)

**Comment by nerd** [comment]
@austinv11 do I have to manually upload files?

**Comment by austinv11** [comment]
Sorry for the late reply. But I usually use gradle and I know that there is a bintray plugin for that, but I believe you can use [Artifactory](https://www.jfrog.com/confluence/display/RTF/Maven+Artifactory+Plugin) to [push to bintray](https://www.jfrog.com/confluence/display/RTF/Push+to+Bintray)

**Comment by admiral0** [comment]
Actually no. You can push to bintray releases. I know how to do it in gradle, not in maven. Would you accept a pull request for a move to gradle?

**Comment by Sponges** [comment]
Heh, you could probably get this on maven central anyway ;) http://central.sonatype.org/

**Comment by demortes** [comment]
Any update on this?

**Comment by austinv11** [comment]
According to nerd, this project is dead (see #18). However my maintained fork located [here](https://github.com/austinv11/Discord4J) has a maven repo as you could read about in the README.
