### ISSUE TITLE
Reconnect after disconnect?

### ISSUE THREAD

**Issue by Ratismal** [nerd/Discord4J#20]
Hi,

Occasionally, the discord bot will disconnect with reason UNKNOWN. In my disconnect event listener, I check if the disconnect reason is unwanted, and if so attempt to reconnect the bot. 

```java
    @EventSubscriber
    public void onDisconnect(DiscordDisconnectedEvent event) throws Exception {
        LogHelper.info("Disconnected (" + event.getReason().name() + ")");
        if (event.getReason() == DiscordDisconnectedEvent.Reason.UNKNOWN ||
                event.getReason() == DiscordDisconnectedEvent.Reason.TIMEOUT ||
                event.getReason() == DiscordDisconnectedEvent.Reason.MISSED_PINGS) {
            try {
                //reconnect here
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```

However, none of the ways I've tried have actually successfully reconnected the bot.
I've tried

- Using the IDiscordClient#login() method on my client instance
- Building a new client from scratch

Using the login() method on an existing client logs a "Disconnected (RECONNECTING)" message, but the bot never comes back with either method. How is one supposed to implement auto-reconnecting? Is there a feature that I'm simply missing? Any help with this would be greatly appreciated.

Thank you for your time,
Ratismal

**Comment by nerd** [comment]
hey,

austinv11 is the guy who maintains this project now. you should probably move this issue over there.
https://github.com/austinv11/Discord4J

**Comment by Ratismal** [comment]
Whoops, I thought that I was on austinv11's fork. My apologies.
