### ISSUE TITLE
Using annotations for listeners rather than interfaces

### ISSUE THREAD

**Issue by austinv11** [nerd/Discord4J#8]
With the new system, events are handled by listeners implementing IListener<? extends IEvent>, however this system can be streamlined since this means there needs to be a new class to handle every event. This could be done by using annotations on methods and registering just a general object and/or class so that when an event is posted, the parameters of each method in a class with an annotation can be checked if it handles the event.

Kind of hard to explain so I think it would be better if I showed you how I did it:
* [Handling events and listeners](https://github.com/austinv11/DiscordBot/blob/2e8d3d61d9e57ddf341d12e7b78034e8af7dacab/src/main/java/com/austinv11/DiscordBot/api/EventBus.java#L31-L98)
* [Example of a class utilizing this system](https://github.com/austinv11/DiscordBot/blob/2e8d3d61d9e57ddf341d12e7b78034e8af7dacab/src/main/java/com/austinv11/DiscordBot/handler/BaseHandler.java)

I just prefer this method, but it's fine if you keep your current way of handling events.

**Comment by nerd** [comment]
Yep, I've written similarly styled event systems before, so I know what you're talking about. I could add it as another way of doing it.

**Comment by nerd** [comment]
Hey, I've pushed another EventDispatcher system using this method.

**Comment by austinv11** [comment]
Awesome, thanks!
